// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

// // Update user
// export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
// export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
// export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL"


// new user
export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL"



// cargar user
export const LOAD_USER_REQUEST="LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL="LOAD_USER_FAIL"



// cargar user
export const LOGOUT_SUCCESS="LOGOUT_SUCCESST"
export const LOGOUT_FAIL="LOGOUT_FAIL"




// UPDATE USER LOGEADO
export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET="UPDATE_PROFILE_RESET"




// UPDATE PASSWORD USUARIO LOGEADO
export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAIL="UPDATE_PASSWORD_FAIL"
export const UPDATE_PASSWORD_RESET="UPDATE_PASSWORD_RESET"


// CONTRASEÑA OLVIDADA
export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL"



// CONTRASEÑA OLVIDADA SEGUNDA PARTE
export const NEW_PASSWORD_REQUEST="NEW_PASSWORD_REQUEST"
export const NEW_PASSWORD_SUCCESS="NEW_PASSWORD_SUCCESS"
export const NEW_PASSWORD_FAIL="NEW_PASSWORD_FAIL"
















// Eliminar errores
export const CLEAR_ERRORS = "CLEAR_ERRORS"





